### PR TITLE
chore: format the code with prettier

### PR DESCRIPTION
**Pull request by michael-go**
- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/dep-graph/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

format & lint the code also with https://prettier.io/

using 1.x and not 2.x as 2.x doesn't support Node 8

### CODE REVIEW

**Comment by darscan** [comment]
Prettier fails on node 8!?

**Comment by michael-go** [comment]
yep version 2.x deprecated node 8

**Comment by darscan** [comment]
should be fine.. we don't need to lint on every version we support.. one linting is enough :D

**Comment by michael-go** [comment]
true :) what's the niceset way to skip it based on version?

**Comment by michael-go** [comment]
I'll just use prettier 1.x instead 🤷‍♂

**Pull request merged**
