### PR TITLE
fix: Bump dependencies

### PR DESCRIPTION
**Pull request by darscan**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/dep-graph/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

- Routine dep maintenance
- Also: make `prettier` a dev dep! 🙈 
- `object-hash` major upgrade is safe https://github.com/puleos/object-hash#v200
- Had to disable silly `tslint` array rule after upgrade

### CODE REVIEW

**Comment by DanielRuf** [comment]
This breaks setups as `semver`7.0.0 set the minimum required node version to >=10.

You should not bump the major version of dependencies in a normal minor release =)

See also https://github.com/verdaccio/generator-verdaccio-plugin/pull/26

**Comment by DanielRuf** [comment]
Afaik the latest npm versions ignored the engine restrictions (regression?) when `npm i` was used.

When we use yarn we can reproduce the failing build:

```
➜  dep-graph git:(master) ✗ nodenv local 8.16.0
➜  dep-graph git:(master) ✗ rm -rf node_modules 
rm %                                                                                                                                                                                 ➜  dep-graph git:(master) ✗ rm yarn.lock 
➜  dep-graph git:(master) ✗ yarn
yarn install v1.22.4
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
[3/5] 🚚  Fetching packages...
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by DanielRuf** [comment]
Trying to replicate the build environment:

https://travis-ci.com/github/snyk/dep-graph/jobs/328140595#L199

So Node 8.17.0 and npm 6.13.4 (pretty old I think) are used.
Let's see if the npm version makes a difference.

**Comment by DanielRuf** [comment]
Argh, still broken in npm@latest, the `engines` check is not done:

```
➜  dep-graph git:(master) ✗ npm -v             
6.14.5
➜  dep-graph git:(master) ✗ npm i              
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> @snyk/dep-graph@ prepare /Users/danielruf/projects/dep-graph
> npm run build
```

**Comment by DanielRuf** [comment]
See https://github.com/npm/cli/issues/1132 and https://github.com/npm/cli/issues/692 - not sure when this has changed. But this is one of the reasons why we use yarn in most projects.

**Comment by darscan** [comment]
@DanielRuf Thanks!

https://github.com/snyk/dep-graph/pull/62

> You should not bump the major version of dependencies in a normal minor release =)

Kinda, sorta, maybe, sometimes, not always =) In this case, yes, given the dependency in question dropped support for Node versions that we still wish to support. Had it not done that, the bump would have been fine, as the `dep-graph` `api` did not change at all (and dependencies are, for the most part, internal implementation details).

Anyhow, thanks for reporting. This should be released tomorrow.

**Pull request merged**
