### PR TITLE
feat: add memoization when converting tree to graph

### PR DESCRIPTION
**Pull request by admons**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/dep-graph/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Like https://github.com/snyk/dep-graph/pull/73 (which affects graphToDepTree), It adds memoization in the depTreeToGraph

For a **very large tree** (that was generated using the memoization from https://github.com/snyk/dep-graph/pull/73), it reduced the time from 20000ms to less than 200ms

### CODE REVIEW

**Comment by FauxFaux** [comment]
Like with the other PR, this appears to just leak memory forever, unless we're planning to use it perfectly in all cases. Isn't there some kind of `lru-cache` for this?

**Comment by robcresswell** [comment]
https://github.com/dominictarr/bench-lru if you do go that route

**Comment by darscan** [comment]
@FauxFaux I don't think either of the PRs leaks memory. In both cases GC will clean up the maps themselves at some point after the operation is complete. Also, the values/keys in the maps are already in memory and shared by the output instances. What are you seeing that I'm not?

Also, I don'r see how an `lru` would help.. there is no global state in either of the PRs

**Comment by FauxFaux** [comment]
I WAS WRONG IGNORE ME.

**Comment by darscan** [comment]
For posterity: the concern was around how default argument initialisers are evaluated in JS (versus Python, for example, where this would indeed be problematic)

**Review by darscan — APPROVED** [review]

**Comment by Shesekino** [comment]
> For posterity: the concern was around how default argument initialisers are evaluated in JS (versus Python, for example, where this would indeed be problematic)

because in Python arguments with a **mutable** default value get attached to the function as a "private member" and never get deleted? so the concern was ```memoizationMap``` never getting cleaned because nothing actively cleans it?

**Comment by calvinli** [comment]
Hey all,

Sorry to revive an old-ish thread but I tried this PR and it did not improve the performance of `buildGraph(...)` on a very large JS dependency tree. I found that it was because

```
if (memoizationMap.has(depTree)) {
```

never evaluated to true because `Map.has` uses `Object.is` semantics (same object, instead of identical object). I was only able to get a speedup (which was substantial) by changing the condition to something like

```
    const depTreeObjHash = objectHash(depTree, { excludeKeys: (key => (key === 'dependencies')) }) + objectHash(depTree.dependencies || {}, { excludeValues: true })
    if (memoizationMap.has(depTreeObjHash)) {
        return memoizationMap.get(depTreeObjHash);
    }
```

so I'm wondering whether the behavior in this PR was intentional.

**Comment by darscan** [comment]
Hi @calvinli . Apologies for the delay.

> never evaluated to true because `Map.has` uses `Object.is` semantics

Yep, unfortunately that was intentional - this was just a small optimisation following on from https://github.com/snyk/dep-graph/pull/73 so it only helps in that particular case.

Some tools (like `npm`) can produce trees where sub trees that appear equivalent from the outside are not, so we have to use full object hashing to pick them up and preserve them properly when converting them to graphs. We can't just look at the direct deps of each dep as your example does (by using `excludeValues`). For example:

```
DepA@1.0.0
- DepX@1.0.0
  - DepY@1.0.1

DepA@1.0.0
- DepX@1.0.0
  - DepY@1.0.2
```

Your change would consider both instances of `DepA@1.0.0` as equivalent, but they are not.

Having to compare sub trees like this makes the conversion very expensive indeed. The goal is to build dep-graphs directly (instead of trees) so that we can avoid this issue entirely.

**Pull request merged**
